### ISSUE TITLE
Broken Link in src/App.js

### ISSUE THREAD

**Issue by ben-nathanson** [City-Bureau/city-scrapers-events#3]
There's a reference to `cityscrapers.org/agency` on line 51 of `src/App.js` that returns a 404, causing a TypeError at runtime. This doesn't seem to be a fatal error - events still render and the [events page](https://city-bureau.github.io/city-scrapers-events/) looks "normal" to me. 

Details:
```
Unhandled Rejection (TypeError): Cannot read property 'cityscrapers.org/agency' of undefined

(anonymous function)
src/App.js:51

  48 | .then(text => {
  49 |   let data = text.split('\n').filter(l => l.trim()).map(JSON.parse);
  50 |   const events = data.map((e) => {
> 51 |     e.agency = e.extra["cityscrapers.org/agency"];
  52 |     e.start = moment.tz(e.start_time, e.timezone);
  53 |     e.end = moment.tz(e.end_time, e.timezone);
  54 |     return e;

(anonymous function)
src/App.js:50
  47 | .then(res => res.text())
  48 | .then(text => {
  49 |   let data = text.split('\n').filter(l => l.trim()).map(JSON.parse);
> 50 |   const events = data.map((e) => {
  51 |     e.agency = e.extra["cityscrapers.org/agency"];
  52 |     e.start = moment.tz(e.start_time, e.timezone);
  53 |     e.end = moment.tz(e.end_time, e.timezone);
```

**Comment by pjsier** [comment]
This looks like it might be on an older fork. The current version allows for `extra` or `extras` because of a shift to match the OCD event schema more closely: 

https://github.com/City-Bureau/city-scrapers-events/blob/6b1318dd0eaa40c3dd0de8fc5cd75d6c842d3397/src/App.js#L62

Closing this since it's fixed in the current repo template, but you're welcome to take what's here and incorporate it into your fork!

**Comment by ben-nathanson** [comment]
This was an older fork -- after merging in the latest changes to my fork we are up and running with 0 errors. 

Still not 100% sure I understand what "cityscrapers.org/agency" does. My assumption was that when I requested the URL "cityscrapers.org/agency" in my browser, I shouldn't get a 404. But my grasp of React is pretty limited at this point so this might be a non-issue for practical purposes. 

Thanks for all your work!
